###
GET http://localhost:3000/ping
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/stores-csv
Authorization: Basic TWFzdGVyczpBY2FkZW15
### File not exist:
PUT http://localhost:3000/stores-csv/optimize/1.json HTTP/1.1
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/discount/callback
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/discount/promise
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/discount/async-await
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/goods/with-max-cost
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/goods?parameter=type&value=socks
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/goods?parameter=quantity&value=0
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/goods/standardize
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/goods/switch?storage=store
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
GET http://localhost:3000/goods/switch?storage=json
Authorization: Basic TWFzdGVyczpBY2FkZW15
###
POST http://localhost:3000/goods/new-data HTTP/1.1
content-type: application/json
Authorization: Basic TWFzdGVyczpBY2FkZW15

[
  {
    "type": "socks",
    "color": "red",
    "quantity": 10,
    "priceForPair": "$3"
  },
  {
    "type": "hat",
    "color": "red",
    "quantity": 7,
    "price": "$5"
  },
  {
    "type": "socks",
    "color": "red",
    "quantity": 10,
    "priceForPair": "$3"
  },
  {
    "type": "hat",
    "color": "red",
    "quantity": 1,
    "price": "$6"
  }
]
###
