# root
GET http://localhost:3000/
###
GET http://localhost:3000/good-with-max-cost
###
GET http://localhost:3000/good?parameter=type&value=socks
###
GET http://localhost:3000/good?parameter=quantity&value=0
###
GET http://localhost:3000/standardize
###
GET http://localhost:3000/change?storage=store
###
GET http://localhost:3000/change?storage=json
###
POST http://localhost:3000/new-data HTTP/1.1
content-type: application/json

[
  {
    "type": "socks",
    "color": "red",
    "quantity": 10,
    "priceForPair": "$3"
  },
  {
    "type": "hat",
    "color": "red",
    "quantity": 7,
    "price": "$5"
  },
  {
    "type": "socks",
    "color": "red",
    "quantity": 10,
    "priceForPair": "$3"
  },
  {
    "type": "hat",
    "color": "red",
    "quantity": 1,
    "price": "$6"
  }
]
###
